backend:
  name: proxy
  proxy_url: https://hansen-api.onrender.com/api/decap-proxy
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: globalComponents
    label: Global Components
    extension: json
    format: json
    editor:
      preview: false
    files:
      - label: Promotions Component
        name: promotions
        file: content/global-components/promotions.json
        fields:
          - name: label
            label: Block Label
            widget: string
          - name: icon # ← Добавить это
            label: Icon
            widget: string
          - name: items
            label: Cards
            widget: list
            summary: "{{fields.title}}"
            label_singular: card
            fields:
              - name: image
                label: Image
                widget: image
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: string
              - name: buttonLabel
                label: Button Label
                widget: string
